### ISSUE TITLE
[Android] App crash

### ISSUE THREAD

**Issue by fatiherdogan01** [Teknasyon-Teknoloji/deepwall-react-native-sdk#34]
Hi,
### Versions
react-native: 0.66.4
deepwall-react-native-sdk: 2.9.3
com.android.tools.build:gradle: 4.2.2
### Description
I need help. I have two issues.
1. When i want to send extra parameter i get this crash

```js
java.lang.IllegalArgumentException: Could not convert class java.util.HashMap
        at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:316)
        at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:312)
        ....
        ....
```
2. When i click any button (close, subscribe, etc.) in Paywall i get this crash

  ```js
TypeError: h.playTouchSound is not a function. (In 'h.playTouchSound()', 'h.playTouchSound' is undefined)
  ```
----
Did you test RN 0.64.x and above? 
Can you help me? @semiherdogan @Fatihakkul

**Comment by semiherdogan** [comment]
Hi, 
thanks for letting us know this issues,
for the first issue we have fixed and will release new version soon.
for the second issue we are upgrading themes on dashboard, they will be ready soon.

**Comment by semiherdogan** [comment]
can you try with version 3.0.0?

**Comment by fatiherdogan01** [comment]
First issue resolved with version 3.0.0.

**Comment by fatiherdogan01** [comment]
Any update for second issue? We want to use this library.

**Comment by semiherdogan** [comment]
Hi,
about the second issue, 
we have upgraded themes on dashboard. In order to use new upgraded themes you need to go to paywall list then, press upgrade paywall button.
Some themes may not have receive update at the moment, if your themes missing upgrade please write to support about this, and they will upgrade your themes.

Im closing this issue, please let us know if any other error occurs.
