### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by fatiherdogan01** [Teknasyon-Teknoloji/deepwall-react-native-sdk#40]
Hi,

The page opens 1-2 seconds after the user interacts. (when poor internet connection)

This flow is happening:
```
deepWallPaywallRequested
deepWallPaywallResponseReceived
deepWallPaywallOpened
```
Maybe we can show loading indicator during this flow. Or any other solution.

Thanks.

**Comment by semiherdogan** [comment]
Hi,

We didn't add this into sdk because some apps may want custom loaders, so we are triggering events for this.

You can have this (showing loader) functionality by listening events. 
As you mentioned when you receive "deepWallPaywallRequested" event, you can show loader (or when user press show paywall button) and when you receive "deepWallPaywallResponseReceived" event you can hide loader.

Please let us know if you need further information.

**Comment by fatiherdogan01** [comment]
Understood. Of course I can do it by listening events. I thought it would be better if it was displayed within the page. 

Thanks.
